version: '3.8'

volumes:
  sqlserver_sqlserver_data: 
  
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=acaf373
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    volumes:
      - sqlserver_sqlserver_data:/var/opt/mssql
    restart: always
  sqlserver.configurator:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    depends_on:
      - sqlserver
    command: >
      bash -c '
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P acaf373 -d master -i docker-entrypoint-initdb.d/init.sql;
      echo "All done!";
      '